/**
 * Loader for per-entity dashboard JSON files.
 *
 * Files live under `static/data/entity_dashboards/<type>/<id>.json` and are
 * generated by `scripts/precompute_entity_dashboards.py`. Each JSON contains
 * every chart-key payload needed to render a detail-page dashboard.
 *
 * The loader is best-effort: missing files return `null` rather than throwing,
 * so the calling page can fall back to an on-the-fly render or a placeholder.
 */

import { base } from '$app/paths';
import type { EntityDashboardData, EntityType } from '$lib/components/dashboards';
import { transformMongoJSON } from './mongoJSON';

/**
 * Path mapping for per-entity JSON files. Keeps slugs aligned with the
 * precompute pipeline's output directory layout.
 */
const ENTITY_DIR: Record<EntityType, string> = {
	language: 'languages',
	subject: 'subjects',
	tag: 'tags',
	person: 'people',
	institution: 'institutions',
	genre: 'genres',
	'resource-type': 'resource-types',
	group: 'groups',
	location: 'locations',
	'research-section': 'research-sections',
	project: 'projects',
	'research-item': 'research-items'
};

/**
 * Load precomputed dashboard data for a single entity.
 *
 * @param entityType - Kind of entity (e.g. `'language'`, `'subject'`).
 * @param id - URL-safe identifier (language code, entity slug, project id, …).
 * @returns the dashboard data, or `null` if the file doesn't exist.
 */
export async function loadEntityDashboard(
	entityType: EntityType,
	id: string
): Promise<EntityDashboardData | null> {
	const dir = ENTITY_DIR[entityType];
	if (!dir) {
		console.warn(`Unknown entity type: ${entityType}`);
		return null;
	}

	const path = `${base}/data/entity_dashboards/${dir}/${encodeURIComponent(id)}.json`;

	try {
		const response = await fetch(path);
		if (!response.ok) {
			if (response.status !== 404) {
				console.warn(`Failed to load ${path}: ${response.status}`);
			}
			return null;
		}
		const raw = await response.json();
		return transformMongoJSON<EntityDashboardData>(raw);
	} catch (err) {
		console.warn(`Error loading ${path}`, err);
		return null;
	}
}

/** Manifest shape, emitted by the precompute pipeline. */
export interface EntityDashboardManifestEntry {
	id: string;
	name: string;
	count: number;
}

export type EntityDashboardManifest = Partial<Record<EntityType, EntityDashboardManifestEntry[]>>;

/**
 * Load the global manifest listing all precomputed per-entity dashboards.
 * Useful for picker UIs or generating sitemap entries.
 */
export async function loadEntityDashboardManifest(): Promise<EntityDashboardManifest> {
	const path = `${base}/data/entity_dashboards/manifest.json`;
	try {
		const response = await fetch(path);
		if (!response.ok) return {};
		return (await response.json()) as EntityDashboardManifest;
	} catch {
		return {};
	}
}
