/**
 * Loader for per-entity dashboard JSON files.
 *
 * Files live under `static/data/entity_dashboards/<type>/<id>.json` and are
 * generated by `scripts/precompute_entity_dashboards.py`. Each JSON contains
 * every chart-key payload needed to render a detail-page dashboard.
 *
 * The loader is best-effort: missing files return `null` rather than throwing,
 * so the calling page can fall back to an on-the-fly render or a placeholder.
 */

import { base } from '$app/paths';
import type { EntityDashboardData, EntityType } from '$lib/components/dashboards';
import { slugify } from '$lib/utils/slugify';
import { transformMongoJSON } from './mongoJSON';
import { fetchJSON } from './fetchHelpers';

/**
 * Path mapping for per-entity JSON files. Keeps slugs aligned with the
 * precompute pipeline's output directory layout.
 */
const ENTITY_DIR: Record<EntityType, string> = {
	language: 'languages',
	subject: 'subjects',
	tag: 'tags',
	person: 'people',
	institution: 'institutions',
	genre: 'genres',
	'resource-type': 'resource-types',
	group: 'groups',
	location: 'locations',
	'research-section': 'research-sections',
	project: 'projects',
	'research-item': 'research-items'
};

/**
 * Load precomputed dashboard data for a single entity.
 *
 * @param entityType - Kind of entity (e.g. `'language'`, `'subject'`).
 * @param id - URL-safe identifier (language code, entity slug, project id, …).
 * @returns the dashboard data, or `null` if the file doesn't exist.
 */
export async function loadEntityDashboard(
	entityType: EntityType,
	id: string
): Promise<EntityDashboardData | null> {
	const dir = ENTITY_DIR[entityType];
	if (!dir) {
		console.warn(`Unknown entity type: ${entityType}`);
		return null;
	}

	// Language codes are already simple ASCII; for every other entity type we
	// slugify the display name so the runtime URL matches the filename that
	// `scripts/precompute_entity_dashboards.py` writes to disk. Keep this
	// aligned with `src/lib/utils/slugify.ts`.
	const slug = entityType === 'language' ? id.toLowerCase() : slugify(id);
	const path = `${base}/data/entity_dashboards/${dir}/${encodeURIComponent(slug)}.json`;

	return fetchJSON<EntityDashboardData>(path, {
		transform: (raw) => transformMongoJSON<EntityDashboardData>(raw),
		warnLevel: 'non-404'
	});
}

/** Manifest shape, emitted by the precompute pipeline. */
export interface EntityDashboardManifestEntry {
	id: string;
	name: string;
	count: number;
}

export type EntityDashboardManifest = Partial<Record<EntityType, EntityDashboardManifestEntry[]>>;

/**
 * Reverse of `ENTITY_DIR`: map directory name → EntityType. Used to remap
 * the manifest's on-disk keys (`people`, `institutions`, …) onto the
 * `EntityType` union (`person`, `institution`, …) so callers can index the
 * returned record by EntityType the way the type declares.
 */
const DIR_TO_ENTITY: Record<string, EntityType> = Object.fromEntries(
	(Object.entries(ENTITY_DIR) as [EntityType, string][]).map(([k, v]) => [v, k])
);

/**
 * Load the global manifest listing all precomputed per-entity dashboards.
 * Useful for picker UIs or generating sitemap entries.
 *
 * The on-disk JSON is keyed by directory name (`people`, `institutions`,
 * `subjects`, …); we remap to the `EntityType` union so the returned shape
 * matches the type signature.
 */
export async function loadEntityDashboardManifest(): Promise<EntityDashboardManifest> {
	const raw = await fetchJSON<Record<string, EntityDashboardManifestEntry[]>>(
		`${base}/data/entity_dashboards/manifest.json`
	);
	if (!raw) return {};
	const result: EntityDashboardManifest = {};
	for (const [dir, entries] of Object.entries(raw)) {
		const entityType = DIR_TO_ENTITY[dir];
		if (entityType) result[entityType] = entries;
	}
	return result;
}
