import type { PublicationsPayload } from '$lib/types';
import { fetchJSON } from './fetchHelpers';

/** URL of the publications dataset relative to a build's basePath. Kept out
 *  of `DATA_PATHS` because publications.json is generated by a different
 *  Python pipeline (`scripts/fetch_eref_publications.py`) than the rest of
 *  the data and may legitimately be absent on a fresh clone. */
export const PUBLICATIONS_PATH = (basePath: string = '') => `${basePath}/data/publications.json`;

/** Fetch the cluster publications dataset. Resolves to `null` if the file
 *  isn't present (e.g. before the fetcher has been run) so the route can
 *  degrade to an empty state rather than erroring out. */
export async function loadPublications(basePath: string = ''): Promise<PublicationsPayload | null> {
	return fetchJSON<PublicationsPayload>(PUBLICATIONS_PATH(basePath), {
		warnLevel: 'non-404',
		contextLabel: 'publications.json'
	});
}
