<script lang="ts">
	import {
		StatCard,
		ChartCard,
		EmptyState,
		Card,
		CardContent,
		Tabs,
		Select,
		SEO
	} from '$lib/components/ui';
	import { NetworkGraph } from '$lib/components/charts';
	import { base } from '$app/paths';
	import { allCollections, persons, projects, ensureCollections } from '$lib/stores/data';
	import {
		buildContributorNetwork,
		buildPersonCollaborationNetwork,
		buildPersonInstitutionNetwork,
		buildInstitutionCollaborationNetwork
	} from '$lib/utils/dataTransform';
	import { universityOptions } from '$lib/types';
	import type { NetworkData } from '$lib/types';
	import { EXTERNAL_SOURCE_ID } from '$lib/utils/dataLoader';
	import type { CollectionItem } from '$lib/types';
	import {
		Circle,
		Link,
		Tag,
		Building2,
		Users,
		Briefcase,
		Sparkles,
		Network as NetworkIcon,
		Maximize2,
		Minimize2
	} from '@lucide/svelte';
	import { SvelteSet, SvelteMap } from 'svelte/reactivity';
	import { onMount } from 'svelte';

	const networkUniversityOptions = [
		...universityOptions,
		{ value: EXTERNAL_SOURCE_ID, label: 'External' }
	];

	const tabs = [
		{ id: 'contributors', label: 'Contributors ↔ Projects' },
		{ id: 'collab', label: 'Co-authorship' },
		{ id: 'affiliations', label: 'People ↔ Institutions' },
		{ id: 'institutions', label: 'Institution collaborations' },
		{ id: 'communities', label: 'Discursive communities' }
	];

	let activeTab = $state('contributors');

	// Filters
	let selectedUniversity = $state('all');
	let maxNodes = $state(120);
	let selectedResourceType = $state('all');

	// Get unique resource types
	let resourceTypeOptions = $derived.by(() => {
		const types = new SvelteSet<string>();
		$allCollections.forEach((item) => {
			if (item.typeOfResource) types.add(item.typeOfResource);
		});
		return [
			{ value: 'all', label: 'All Resource Types' },
			...Array.from(types)
				.sort()
				.map((t) => ({ value: t, label: t }))
		];
	});

	let filteredCollections = $derived.by(() => {
		let result: CollectionItem[] = $allCollections;
		if (selectedUniversity !== 'all') {
			result = result.filter((item) => item.university === selectedUniversity);
		}
		if (selectedResourceType !== 'all') {
			result = result.filter((item) => item.typeOfResource === selectedResourceType);
		}
		return result;
	});

	let contributorNetwork = $derived(buildContributorNetwork(filteredCollections, maxNodes));
	let collabNetwork = $derived(buildPersonCollaborationNetwork(filteredCollections, maxNodes));
	let affiliationNetwork = $derived(buildPersonInstitutionNetwork($persons, 80));
	let institutionNetwork = $derived(
		buildInstitutionCollaborationNetwork($projects, $persons, maxNodes)
	);

	// -------------------------------------------------------------------------
	// Discursive-communities view: load the Louvain output generated by the
	// Python pipeline. We render the top-PageRank nodes linked by the strongest
	// global edges, coloured by community.
	// -------------------------------------------------------------------------
	interface MetaCommunity {
		id: number;
		label: string;
		count: number;
	}
	interface MetaNode {
		id: string;
		label: string;
		type: string;
		category: number;
		importance: number;
		cluster: number;
	}
	interface MetaPayload {
		nodes_total: number;
		edges_total: number;
		communities: MetaCommunity[];
		top_nodes: MetaNode[];
	}

	let meta = $state<MetaPayload | null>(null);
	let metaError = $state(false);

	onMount(async () => {
		void ensureCollections(base);
		try {
			const resp = await fetch(`${base}/data/knowledge_graphs/_meta.json`);
			if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
			meta = await resp.json();
		} catch {
			metaError = true;
		}
	});

	const CATEGORY_NAMES = [
		'Research Item',
		'Person',
		'Subject',
		'Tag',
		'Location',
		'Project',
		'Genre',
		'Institution'
	];

	// Build a graph for the Communities tab: show the top-PageRank node of each
	// community as an "anchor" node, plus lighter nodes for the next few
	// top-ranked members of the same community. Edge: each member linked to its
	// community anchor. This gives the user a 30K-foot view of the discursive
	// field.
	let communityNetwork = $derived.by((): NetworkData | null => {
		if (!meta) return null;
		const nodes: NetworkData['nodes'] = [];
		const links: NetworkData['links'] = [];
		const seen = new SvelteSet<string>();

		// Group top_nodes by cluster, keep top-5 per cluster.
		const byCluster = new SvelteMap<number, MetaNode[]>();
		for (const n of meta.top_nodes) {
			if (n.cluster < 0) continue;
			const arr = byCluster.get(n.cluster) ?? [];
			arr.push(n);
			byCluster.set(n.cluster, arr);
		}
		for (const [cid, members] of byCluster) {
			members.sort((a, b) => b.importance - a.importance);
			const anchor = members[0];
			if (!anchor) continue;
			// Add anchor node
			if (!seen.has(anchor.id)) {
				nodes.push({
					id: anchor.id,
					name: anchor.label,
					category: anchor.category,
					symbolSize: Math.max(24, Math.min(52, 20 + anchor.importance * 28)),
					cluster: cid,
					importance: anchor.importance
				});
				seen.add(anchor.id);
			}
			for (const m of members.slice(1, 5)) {
				if (!seen.has(m.id)) {
					nodes.push({
						id: m.id,
						name: m.label,
						category: m.category,
						symbolSize: Math.max(10, Math.min(26, 10 + m.importance * 18)),
						cluster: cid,
						importance: m.importance
					});
					seen.add(m.id);
				}
				links.push({
					source: anchor.id,
					target: m.id,
					value: 1 + m.importance * 3,
					label: 'same discursive community',
					relation: 'direct'
				});
			}
		}

		return {
			nodes,
			links,
			categories: CATEGORY_NAMES.map((name) => ({ name })),
			clusters: meta.communities,
			center: undefined
		};
	});

	function handleTabChange(tabId: string) {
		activeTab = tabId;
	}

	// Fullscreen for any of the network views. We stash the active tab's key
	// and render a single overlay -- keeps the markup simple and makes the UX
	// consistent across tabs.
	let fullscreenId = $state<string | null>(null);
	let fullscreenTitle = $state('');

	function enterFullscreen(id: string, title: string) {
		fullscreenId = id;
		fullscreenTitle = title;
		if (typeof document !== 'undefined') document.body.style.overflow = 'hidden';
	}

	function exitFullscreen() {
		fullscreenId = null;
		fullscreenTitle = '';
		if (typeof document !== 'undefined') document.body.style.overflow = '';
	}

	let fullscreenData = $derived.by((): NetworkData | null => {
		if (!fullscreenId) return null;
		switch (fullscreenId) {
			case 'contributors':
				return contributorNetwork;
			case 'collab':
				return collabNetwork;
			case 'affiliations':
				return affiliationNetwork;
			case 'institutions':
				return institutionNetwork;
			case 'communities':
				return communityNetwork;
			default:
				return null;
		}
	});

	// Portal the overlay to <body> so `position: fixed` is guaranteed to be
	// viewport-relative regardless of ancestor containing blocks.
	function toBody(node: HTMLElement) {
		document.body.appendChild(node);
		return {
			destroy() {
				node.remove();
			}
		};
	}
</script>

<SEO
	title="Network"
	description="Explore relationships between contributors, projects, institutions, and discursive communities"
/>

<div class="space-y-6">
	<!-- Page Header -->
	<div class="animate-slide-in-up">
		<h1 class="page-title">Network</h1>
		<p class="page-subtitle">
			Relationships between contributors, projects, institutions, and the discursive communities
			emerging across the archive
		</p>
	</div>

	<!-- Filters -->
	<Card>
		<CardContent class="pt-6">
			<div class="flex flex-wrap items-end gap-4">
				<div class="w-48">
					<span class="text-sm text-muted-foreground mb-1 block">University</span>
					<Select
						options={networkUniversityOptions}
						bind:value={selectedUniversity}
						placeholder="Select university"
					/>
				</div>

				<div class="w-48">
					<span class="text-sm text-muted-foreground mb-1 block">Resource Type</span>
					<Select
						options={resourceTypeOptions}
						bind:value={selectedResourceType}
						placeholder="Select type"
					/>
				</div>

				<div class="w-48">
					<span class="text-sm text-muted-foreground mb-1 block">
						Max Nodes: <span class="font-medium">{maxNodes}</span>
					</span>
					<input
						type="range"
						min="30"
						max="240"
						step="10"
						bind:value={maxNodes}
						class="w-full h-2 bg-muted rounded-lg appearance-none cursor-pointer accent-primary"
					/>
				</div>

				<div class="text-sm text-muted-foreground">
					Showing <span class="font-medium text-foreground">{filteredCollections.length}</span> items
				</div>
			</div>
		</CardContent>
	</Card>

	<!-- Tabs -->
	<Tabs {tabs} {activeTab} onTabChange={handleTabChange}>
		{#snippet children(tab)}
			{#if tab === 'contributors'}
				<!-- Contributor Network -->
				<div class="grid gap-4 md:grid-cols-3 mb-6">
					<StatCard
						value={contributorNetwork.nodes.length}
						label="Nodes (projects + people)"
						icon={Circle}
						animationDelay="75ms"
					/>
					<StatCard
						value={contributorNetwork.links.length}
						label="Weighted contributions"
						icon={Link}
						animationDelay="150ms"
					/>
					<StatCard
						value={contributorNetwork.categories.length}
						label="Categories"
						icon={Tag}
						animationDelay="225ms"
					/>
				</div>

				<ChartCard title="Who contributes to which project" contentHeight="h-chart-2xl">
					{#snippet headerExtra()}
						<button
							type="button"
							onclick={() => enterFullscreen('contributors', 'Who contributes to which project')}
							class="p-2 rounded-lg hover:bg-muted transition-colors"
							aria-label="Fullscreen"
						>
							<Maximize2 class="h-4 w-4 text-muted-foreground" />
						</button>
					{/snippet}
					{#if contributorNetwork.nodes.length > 0}
						<NetworkGraph data={contributorNetwork} />
					{:else}
						<EmptyState message="No network data available" />
					{/if}
				</ChartCard>

				<ChartCard title="How to read this" class="mt-6">
					<div class="space-y-2 text-sm text-muted-foreground max-w-3xl">
						<p>
							Each <span class="font-medium text-foreground">large dot</span> is a
							<span class="font-medium text-foreground">project</span>; each
							<span class="font-medium text-foreground">small dot</span> is a person who has
							contributed research items to one or more projects. An edge means "this person
							contributed to this project", and the
							<span class="font-medium text-foreground">thicker the line</span>, the more items they
							contributed.
						</p>
						<p>
							Hubs -- projects with many contributors, or people working across many projects --
							reveal the busiest collaboration spaces in the archive.
						</p>
					</div>
					<div class="flex gap-6 mt-4">
						{#each contributorNetwork.categories as category, i (category.name ?? i)}
							<div class="flex items-center gap-2">
								<div
									class="w-4 h-4 rounded-full"
									style="background-color: {i === 0
										? 'hsl(var(--chart-1))'
										: 'hsl(var(--chart-2))'}"
								></div>
								<span class="text-sm">{category.name}</span>
							</div>
						{/each}
					</div>
					<p class="text-xs text-muted-foreground mt-3">
						Drag nodes to rearrange. Scroll to zoom. Click-and-drag the background to pan.
					</p>
				</ChartCard>
			{:else if tab === 'collab'}
				<!-- Person-Person Collaboration -->
				<div class="grid gap-4 md:grid-cols-3 mb-6">
					<StatCard
						value={collabNetwork.nodes.length}
						label="Co-authors shown"
						icon={Users}
						animationDelay="75ms"
					/>
					<StatCard
						value={collabNetwork.links.length}
						label="Collaboration edges"
						icon={Link}
						animationDelay="150ms"
					/>
					<StatCard
						value={filteredCollections.length}
						label="Items analysed"
						icon={Circle}
						animationDelay="225ms"
					/>
				</div>

				<ChartCard title="Who co-authors with whom" contentHeight="h-chart-2xl">
					{#snippet headerExtra()}
						<button
							type="button"
							onclick={() => enterFullscreen('collab', 'Who co-authors with whom')}
							class="p-2 rounded-lg hover:bg-muted transition-colors"
							aria-label="Fullscreen"
						>
							<Maximize2 class="h-4 w-4 text-muted-foreground" />
						</button>
					{/snippet}
					{#if collabNetwork.nodes.length > 0}
						<NetworkGraph
							data={collabNetwork}
							forceConfig={{
								repulsion: 260,
								gravity: 0.05,
								edgeLength: [80, 180],
								friction: 0.5
							}}
						/>
					{:else}
						<EmptyState
							message="No collaboration pairs found -- most items have only one listed contributor."
						/>
					{/if}
				</ChartCard>

				<ChartCard title="How to read this" class="mt-6">
					<p class="text-sm text-muted-foreground max-w-3xl">
						An edge joins two people who appear as contributors on the same research item. The
						<span class="font-medium text-foreground">thicker the edge</span>, the more items they
						co-authored together. We drop one-off pairings (a single shared item) so that only
						repeated, meaningful collaborations remain. The
						<span class="font-medium text-foreground">larger a node</span>, the more collaborators
						that person has, so the biggest nodes identify the archive's most connective scholars.
					</p>
					<p class="text-xs text-muted-foreground mt-3">
						This view is a projection of the contributor-project bipartite graph -- the same
						authorship data, viewed through the "shared neighbourhood" lens rather than
						edge-by-edge.
					</p>
				</ChartCard>
			{:else if tab === 'affiliations'}
				<!-- Affiliation Network -->
				<div class="grid gap-4 md:grid-cols-3 mb-6">
					<StatCard
						value={affiliationNetwork.nodes.length}
						label="Nodes"
						icon={Circle}
						animationDelay="75ms"
					/>
					<StatCard
						value={affiliationNetwork.links.length}
						label="Connections"
						icon={Link}
						animationDelay="150ms"
					/>
					<StatCard
						value={$persons.length}
						label="Total persons"
						icon={Users}
						animationDelay="225ms"
					/>
				</div>

				<ChartCard title="Which institutions each person belongs to" contentHeight="h-chart-2xl">
					{#snippet headerExtra()}
						<button
							type="button"
							onclick={() =>
								enterFullscreen('affiliations', 'Which institutions each person belongs to')}
							class="p-2 rounded-lg hover:bg-muted transition-colors"
							aria-label="Fullscreen"
						>
							<Maximize2 class="h-4 w-4 text-muted-foreground" />
						</button>
					{/snippet}
					{#if affiliationNetwork.nodes.length > 0}
						<NetworkGraph data={affiliationNetwork} />
					{:else}
						<EmptyState
							message="No affiliation data available. Persons may not have institutional affiliations recorded."
						/>
					{/if}
				</ChartCard>

				<ChartCard title="How to read this" class="mt-6">
					<p class="text-sm text-muted-foreground max-w-3xl">
						This is a bipartite map: people on one side, institutions on the other. An edge means
						"this person is affiliated with this institution". People with multiple affiliations act
						as <span class="font-medium text-foreground">bridges</span> between institutions -- trace
						them to see how knowledge flows across the archive's institutional geography.
					</p>
					<div class="flex gap-6 mt-4">
						{#each affiliationNetwork.categories as category, i (category.name ?? i)}
							<div class="flex items-center gap-2">
								<div
									class="w-4 h-4 rounded-full"
									style="background-color: {i === 0
										? 'hsl(var(--chart-1))'
										: 'hsl(var(--chart-2))'}"
								></div>
								<span class="text-sm">{category.name}</span>
							</div>
						{/each}
					</div>
				</ChartCard>
			{:else if tab === 'institutions'}
				<!-- Institution Collaboration Network -->
				<div class="grid gap-4 md:grid-cols-3 mb-6">
					<StatCard
						value={institutionNetwork.nodes.length}
						label="Institutions"
						icon={Building2}
						animationDelay="75ms"
					/>
					<StatCard
						value={institutionNetwork.links.length}
						label="Collaborations"
						icon={Link}
						animationDelay="150ms"
					/>
					<StatCard
						value={$projects.length}
						label="Total projects"
						icon={Briefcase}
						animationDelay="225ms"
					/>
				</div>

				<ChartCard title="Institution collaboration network" contentHeight="h-chart-2xl">
					{#snippet headerExtra()}
						<button
							type="button"
							onclick={() => enterFullscreen('institutions', 'Institution collaboration network')}
							class="p-2 rounded-lg hover:bg-muted transition-colors"
							aria-label="Fullscreen"
						>
							<Maximize2 class="h-4 w-4 text-muted-foreground" />
						</button>
					{/snippet}
					{#if institutionNetwork.nodes.length > 0}
						<NetworkGraph data={institutionNetwork} />
					{:else}
						<EmptyState
							message="No collaboration data available. Institutions may not have shared projects."
						/>
					{/if}
				</ChartCard>

				<ChartCard title="How to read this" class="mt-6">
					<p class="text-sm text-muted-foreground max-w-3xl">
						Institutions connect when they have people on the same project together. The
						<span class="font-medium text-foreground">bigger the node</span>, the more
						collaborations that institution is in. The
						<span class="font-medium text-foreground">thicker the edge</span>, the more projects
						those two institutions share. The densest clumps are the partnerships that anchor
						multi-institutional research; isolated edges at the periphery are one-off
						collaborations.
					</p>
				</ChartCard>
			{:else}
				<!-- Discursive Communities -->
				{#if metaError}
					<EmptyState
						message="Discursive-community data is not available. Run scripts/generate_knowledge_graphs.py to build it."
					/>
				{:else if !meta || !communityNetwork}
					<div class="flex items-center justify-center py-16">
						<p class="text-sm text-muted-foreground animate-pulse">
							Loading global community structure...
						</p>
					</div>
				{:else}
					<div class="grid gap-4 md:grid-cols-3 mb-6">
						<StatCard
							value={meta.communities.length}
							label="Discursive communities"
							icon={Sparkles}
							animationDelay="75ms"
						/>
						<StatCard
							value={meta.nodes_total}
							label="Global nodes"
							icon={NetworkIcon}
							animationDelay="150ms"
						/>
						<StatCard
							value={meta.edges_total}
							label="Global edges"
							icon={Link}
							animationDelay="225ms"
						/>
					</div>

					<ChartCard title="Communities of meaning across the archive" contentHeight="h-chart-2xl">
						{#snippet headerExtra()}
							<button
								type="button"
								onclick={() =>
									enterFullscreen('communities', 'Communities of meaning across the archive')}
								class="p-2 rounded-lg hover:bg-muted transition-colors"
								aria-label="Fullscreen"
							>
								<Maximize2 class="h-4 w-4 text-muted-foreground" />
							</button>
						{/snippet}
						<NetworkGraph data={communityNetwork} showCommunityHalo={true} />
					</ChartCard>

					<ChartCard title="How to read this" class="mt-6">
						<p class="text-sm text-muted-foreground max-w-3xl">
							This view is <em>not</em> a list of metadata triples. Instead, a community-detection
							algorithm (Louvain) ran across the whole archive's knowledge graph and grouped people,
							projects, subjects, items and institutions that sit in densely inter-connected
							neighbourhoods. Each cluster is a
							<span class="font-medium text-foreground">discursive community</span>: a recurring way
							the field organises meaning.
						</p>
						<p class="text-sm text-muted-foreground max-w-3xl mt-2">
							The halo colour on each node indicates which community it belongs to. Big nodes are
							<span class="font-medium text-foreground">key discursive nodes</span>: entities that
							hold a community together (ranked by PageRank over the global graph). Click any node
							to open its full ego graph, where you can see direct metadata edges as well as the
							latent, structural ties that local co-occurrence views miss.
						</p>
						<div class="mt-4">
							<p class="text-sm font-medium">Communities identified</p>
							<div class="flex flex-wrap gap-2 mt-2">
								{#each meta.communities.slice(0, 12) as c (c.id)}
									<span
										class="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs border border-border bg-muted/40"
									>
										<span
											class="inline-block w-2.5 h-2.5 rounded-full"
											style="background-color: {[
												'#6366f1',
												'#14b8a6',
												'#f59e0b',
												'#ec4899',
												'#84cc16',
												'#0ea5e9',
												'#a855f7',
												'#f43f5e',
												'#22c55e',
												'#eab308'
											][c.id % 10]}"
										></span>
										<span class="max-w-[240px] truncate">{c.label}</span>
										<span class="opacity-60">{c.count}</span>
									</span>
								{/each}
								{#if meta.communities.length > 12}
									<span class="text-xs text-muted-foreground self-center">
										+{meta.communities.length - 12} smaller
									</span>
								{/if}
							</div>
						</div>
					</ChartCard>
				{/if}
			{/if}
		{/snippet}
	</Tabs>
</div>

{#if fullscreenId && fullscreenData}
	<div class="fixed inset-0 z-[100] bg-background flex flex-col" use:toBody>
		<div class="flex items-center justify-between px-4 py-3 border-b border-border">
			<h2 class="text-lg font-semibold flex items-center gap-2">
				<NetworkIcon class="h-5 w-5 text-primary" />
				{fullscreenTitle}
			</h2>
			<button
				onclick={exitFullscreen}
				class="p-2 rounded-lg hover:bg-muted transition-colors"
				aria-label="Exit fullscreen"
			>
				<Minimize2 class="h-5 w-5" />
			</button>
		</div>
		<div class="flex-1">
			<NetworkGraph
				data={fullscreenData}
				showCommunityHalo={fullscreenId === 'communities'}
				forceConfig={{
					repulsion: fullscreenId === 'collab' ? 400 : 320,
					gravity: 0.06,
					edgeLength: fullscreenId === 'collab' ? [130, 280] : [110, 240],
					friction: 0.3,
					layoutAnimation: false
				}}
				class="w-full h-full"
			/>
		</div>
	</div>
{/if}
